name: Gradle Package

on:
  push:
    branches: 
      - master
      - r/*
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: ${{ secrets.CONFIG_URL }}
        # New filename to rename the downloaded file
        file-name: izumi-config.yml

    - name: Build with Gradle
      run: gradle build
